# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_ch_ver2.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto_ch_ver2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto_ch_ver2.proto\x12\x07game.ch\"=\n\x0ePB_ThornBallCH\x12\x11\n\tatkpoints\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\x12\x0b\n\x03\x64ir\x18\x03 \x01(\x05\"\x98\x01\n\x13PB_ActorOperationCH\x12\x0f\n\x07\x62lockid\x18\x01 \x01(\x05\x12\x0f\n\x03pos\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x11\n\tblockdata\x18\x03 \x01(\x05\x12\x10\n\x08\x64ropitem\x18\x04 \x01(\x08\x12\x12\n\nwaterPress\x18\x05 \x01(\x05\x12\x17\n\x0flowerWaterPress\x18\x06 \x01(\x05\x12\r\n\x05mapid\x18\x07 \x01(\x05\"_\n\x15PB_StorageBoxPutAllCH\x12\x11\n\tplayeruin\x18\x01 \x01(\r\x12\x11\n\tbaseindex\x18\x02 \x01(\x05\x12\x0f\n\x07\x62lockid\x18\x03 \x01(\x05\x12\x0f\n\x03pos\x18\x04 \x03(\x05\x42\x02\x10\x01\"d\n\x14PB_SyncDyeableItemCH\x12\x11\n\tplayeruin\x18\x01 \x02(\r\x12\r\n\x05index\x18\x02 \x02(\x05\x12\x0e\n\x06itemid\x18\x03 \x02(\x05\x12\x0b\n\x03num\x18\x04 \x02(\x05\x12\r\n\x05sdata\x18\x05 \x02(\t\"O\n\x0ePB_StoveTakeCH\x12\x0f\n\x03pos\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x0b\n\x03uin\x18\x02 \x01(\r\x12\r\n\x05index\x18\x03 \x01(\x05\x12\x10\n\x08taketype\x18\x04 \x01(\x05\"4\n\x13PB_StopweaponanimCH\x12\r\n\x05objid\x18\x01 \x01(\x03\x12\x0e\n\x06\x61nimid\x18\x02 \x01(\x05\"6\n\x15PB_StopweaponmotionCH\x12\r\n\x05objid\x18\x01 \x01(\x03\x12\x0e\n\x06mclass\x18\x02 \x01(\x05\"]\n\x12PB_PlaySkinVoiceCH\x12\x0e\n\x06skinId\x18\x01 \x01(\x05\x12\x11\n\tvoiceType\x18\x02 \x01(\x05\x12\x0f\n\x03pos\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x07uinlist\x18\x04 \x03(\rB\x02\x10\x01\" \n\x0fPB_BoxPlayAniCH\x12\r\n\x05objid\x18\x01 \x01(\x03\"`\n\x0ePB_CustomPbcCH\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0e\n\x06ziplen\x18\x03 \x01(\r\x12\x10\n\x08unziplen\x18\x04 \x01(\r\x12\r\n\x05islua\x18\x05 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_ch_ver2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PB_ACTOROPERATIONCH'].fields_by_name['pos']._loaded_options = None
  _globals['_PB_ACTOROPERATIONCH'].fields_by_name['pos']._serialized_options = b'\020\001'
  _globals['_PB_STORAGEBOXPUTALLCH'].fields_by_name['pos']._loaded_options = None
  _globals['_PB_STORAGEBOXPUTALLCH'].fields_by_name['pos']._serialized_options = b'\020\001'
  _globals['_PB_STOVETAKECH'].fields_by_name['pos']._loaded_options = None
  _globals['_PB_STOVETAKECH'].fields_by_name['pos']._serialized_options = b'\020\001'
  _globals['_PB_PLAYSKINVOICECH'].fields_by_name['pos']._loaded_options = None
  _globals['_PB_PLAYSKINVOICECH'].fields_by_name['pos']._serialized_options = b'\020\001'
  _globals['_PB_PLAYSKINVOICECH'].fields_by_name['uinlist']._loaded_options = None
  _globals['_PB_PLAYSKINVOICECH'].fields_by_name['uinlist']._serialized_options = b'\020\001'
  _globals['_PB_THORNBALLCH']._serialized_start=32
  _globals['_PB_THORNBALLCH']._serialized_end=93
  _globals['_PB_ACTOROPERATIONCH']._serialized_start=96
  _globals['_PB_ACTOROPERATIONCH']._serialized_end=248
  _globals['_PB_STORAGEBOXPUTALLCH']._serialized_start=250
  _globals['_PB_STORAGEBOXPUTALLCH']._serialized_end=345
  _globals['_PB_SYNCDYEABLEITEMCH']._serialized_start=347
  _globals['_PB_SYNCDYEABLEITEMCH']._serialized_end=447
  _globals['_PB_STOVETAKECH']._serialized_start=449
  _globals['_PB_STOVETAKECH']._serialized_end=528
  _globals['_PB_STOPWEAPONANIMCH']._serialized_start=530
  _globals['_PB_STOPWEAPONANIMCH']._serialized_end=582
  _globals['_PB_STOPWEAPONMOTIONCH']._serialized_start=584
  _globals['_PB_STOPWEAPONMOTIONCH']._serialized_end=638
  _globals['_PB_PLAYSKINVOICECH']._serialized_start=640
  _globals['_PB_PLAYSKINVOICECH']._serialized_end=733
  _globals['_PB_BOXPLAYANICH']._serialized_start=735
  _globals['_PB_BOXPLAYANICH']._serialized_end=767
  _globals['_PB_CUSTOMPBCCH']._serialized_start=769
  _globals['_PB_CUSTOMPBCCH']._serialized_end=865
# @@protoc_insertion_point(module_scope)
